sudo: true
before_install:
- openssl aes-256-cbc -K $encrypted_8be31f32afcf_key -iv $encrypted_8be31f32afcf_iv
  -in assets/server.key.enc -out assets/server.key -d
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- export SFDX_AUDIENCE_URL=https://login.salesforce.com
- mkdir sfdx
- wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
before_script:
- export DEPLOYDIR=src
- export TESTLEVEL=RunLocalTests
- export SFURL=https://login.salesforce.com
- export CKEY=3MVG9vrJTfRxlfl6dBs0pvx.BScLRsKzx1S6xpB.gttH9AlgHegTavWdstmTnylyTl0KnvTRQV395j1N0OFny
- export UNAME=rajisvasan@eatrail.com
- sfdx --version
- sfdx plugins --core
script:
- sfdx force:auth:jwt:grant -i $CKEY -f assets/server.key -u $UNAME -r $SFURL -a UAT
- sfdx force:mdapi:deploy -w 10 -d $DEPLOYDIR -u UAT
